version: '3.9'
services:
  nestjs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '8001:8001'
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: todo_server
      DB_HOST: host.docker.internal
      SECRET: super-secret
      GOOGLE_CLIENT_ID: 970731309100-8jba6nln6qd33fflqc4d9qqgm5r24ev3.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./src:/app/src
    depends_on:
      - my-sql
      - redis
    networks:
      - nodejss

  my-sql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_server
      MYSQL_USER: phat
      MYSQL_PASSWORD: phat
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - nodejss
  redis:
    image: redis:7.2.0
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./cache:/data

networks:
  nodejss:
