version: '3.9'
services:
  nestjs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: todo_server
      DB_HOST: host.docker.internal
      SECRET: super-secret
      GOOGLE_CLIENT_ID: 970731309100-8jba6nln6qd33fflqc4d9qqgm5r24ev3.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    volumes:
      - ./src:/app/src
    depends_on:
      - my-sql
    networks:
      - nodejss

  my-sql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_server
      MYSQL_USER: phat
      MYSQL_PASSWORD: phat
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - nodejss

networks:
  nodejss:
